### ISSUE TITLE
关于主线内核的dts没有vpu

### ISSUE THREAD

**Issue by artosynTec** [retro98boy/tn3399-v3-linux#15]
hello~
我看bsp内核的dts里面有关于vpu的配置，但是mainline的dts里面没有关于vpu的配置，所以mainline的`/dev`里面找不到关于vpu的设备；是因为主线内核没办法开启vpu么；
感谢~

**Comment by retro98boy** [comment]
> hello~ 我看bsp内核的dts里面有关于vpu的配置，但是mainline的dts里面没有关于vpu的配置，所以mainline的`/dev`里面找不到关于vpu的设备；是因为主线内核没办法开启vpu么； 感谢~

主线的设备树是开启了vpu的，vpu的设备树节点在rk3399.dtsi中，且没有status属性，那就默认是enabled的

进入Armbian后，可以通过dmesg | grep -i vpu或者dmesg | grep -i video看看，vpu rkvdec等编解码的设备驱动注册的节点为/dev/videox，它使用了V4l2的框架

想在主线内核使用vpu rkvdec编解码，瑞芯微BSP提供的库肯定是不行的，目前可以通过gstreamer stateless codec插件来使用硬件编解码，参考：

https://wiki.pine64.org/wiki/Mainline_Hardware_Decoding

https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1141

**Comment by retro98boy** [comment]
> hello~ 我看bsp内核的dts里面有关于vpu的配置，但是mainline的dts里面没有关于vpu的配置，所以mainline的`/dev`里面找不到关于vpu的设备；是因为主线内核没办法开启vpu么； 感谢~

https://github.com/torvalds/linux/blob/master/arch/arm64/boot/dts/rockchip/rk3399.dtsi

**Comment by artosynTec** [comment]
感谢
